export const styles = {
  app: { fontFamily: "system-ui", padding: 16, maxWidth: 900, margin: "0 auto" },
  topbar: { display: "flex", alignItems: "center", gap: 12, marginBottom: 12 },
  h1: { fontSize: 22, margin: 0 },
  pill: { padding: "6px 10px", borderRadius: 999, border: "1px solid #ddd", background: "#fff" },
  input: { padding: "10px 12px", borderRadius: 10, border: "1px solid #ddd", width: "100%" },
  row: { display: "flex", gap: 10, alignItems: "center" },
  btn: {
    padding: "10px 12px",
    borderRadius: 12,
    border: "1px solid #ddd",
    background: "#fff",
    cursor: "pointer",
    fontWeight: 600,
  },
  btnPrimary: {
    padding: "10px 12px",
    borderRadius: 12,
    border: "1px solid #111",
    background: "#111",
    color: "#fff",
    cursor: "pointer",
    fontWeight: 700,
  },
  card: { border: "1px solid #e5e5e5", borderRadius: 14, padding: 12, background: "#fff" },
  list: { display: "grid", gap: 10 },
  bookRow: { display: "grid", gridTemplateColumns: "56px 1fr", gap: 12, alignItems: "center" },
  cover: { width: 56, height: 72, borderRadius: 10, border: "1px solid #eee", objectFit: "cover", background: "#fafafa" },
  meta: { fontSize: 12, color: "#666", marginTop: 2 },
  label: { fontSize: 12, color: "#444", marginBottom: 6 },
  select: { padding: "10px 12px", borderRadius: 10, border: "1px solid #ddd", width: "100%" },
  divider: { height: 1, background: "#eee", margin: "12px 0" },
  link: { color: "#111", textDecoration: "underline", cursor: "pointer" },
  small: { fontSize: 12, color: "#666" },
};
